---
title: Nubetrosfera
description: Divulgación atmosférica - Página de divulgación científica, recursos didácticos y ocio.
#remote_theme: jekyll/minima
theme: null

# Plugins necesarios para que GitHub Pages no se confunda
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - recursos.md
  - blog.md
  - galeria.md
  - didacticos.md
  - radiocumulus.md

baseurl: "" # Déjalo vacío
url: "https://nubetrosfera.github.io"
---