---
remote_theme: jekyll/minima
title: Nubetrosfera
description: Página de divulgación científica, recursos didácticos y ocio.
email: creativadelamora@gmail.com
header_pages:
  - recursos.md
  - blog.md
  - galeria.md
  - didacticos.md
  - radiocumulus.md
baseurl: "" # Déjalo vacío
url: "https://nubetrosfera.github.io"
---